# Generated by Django 4.2.15 on 2025-01-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myclass', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='vk_link',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
