# Generated by Django 4.2.15 on 2025-01-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myclass', '0002_alter_student_vk_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id_my_class',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='vk_link',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
