# Generated by Django 4.2.15 on 2025-01-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myclass', '0003_alter_student_id_my_class_alter_student_vk_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='id_my_class',
            field=models.IntegerField(unique=True),
        ),
    ]
