# Generated by Django 4.2.15 on 2025-01-04 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('google_sheets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='googlesheet',
            options={'verbose_name': 'Google Таблица', 'verbose_name_plural': 'Google Таблицы'},
        ),
    ]
