# Generated by Django 4.2.15 on 2024-09-15 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        ('users', '0003_alter_user_type_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='staff.typestaff'),
        ),
    ]
