# Generated by Django 4.2.15 on 2024-09-07 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryLibraryStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='TypeStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_staff', models.CharField(max_length=50, verbose_name='Type staff')),
            ],
        ),
        migrations.CreateModel(
            name='LibraryStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('link', models.URLField(verbose_name='Link')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.categorylibrarystaff')),
                ('type_staff', models.ManyToManyField(to='staff.typestaff', verbose_name='Type staff')),
            ],
        ),
        migrations.AddField(
            model_name='categorylibrarystaff',
            name='type_staff',
            field=models.ManyToManyField(to='staff.typestaff', verbose_name='Type staff'),
        ),
    ]
