# Generated by Django 4.2.15 on 2025-08-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorylibrarystaff',
            options={'ordering': ['order', 'category']},
        ),
        migrations.AlterModelOptions(
            name='librarystaff',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='categorylibrarystaff',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='librarystaff',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
    ]
