# Generated by Django 4.2.15 on 2025-08-24 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_categorylibrarystaff_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Section name')),
                ('url_name', models.CharField(max_length=100, verbose_name='URL name')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icon class')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='typestaff',
            name='site_sections',
            field=models.ManyToManyField(blank=True, to='staff.sitesection', verbose_name='Site sections access'),
        ),
    ]
