# Generated by Django 4.2.15 on 2025-01-11 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myclass', '0005_subject_delete_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(verbose_name='Регистрация активна?')),
                ('registration_open_day', models.IntegerField(verbose_name='День недели открытия регистрации (1..7)')),
                ('registration_open_time', models.TimeField(verbose_name='Вермя открытия регистрации')),
                ('registration_close_day', models.IntegerField(verbose_name='День недели окончания регистрации (1..7)')),
                ('registration_close_time', models.TimeField(verbose_name='Вермя окончания регистрации')),
            ],
        ),
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('EGE', 'ЕГЭ'), ('OGE', 'ОГЭ')], max_length=3, verbose_name='Тип экзамена')),
            ],
        ),
        migrations.CreateModel(
            name='MessageBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название сообщение')),
                ('message', models.TextField(verbose_name='Сообщение')),
            ],
        ),
        migrations.CreateModel(
            name='WeekDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='День недели')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование предмета')),
                ('genitive_name', models.CharField(max_length=100, verbose_name='Имя в родительном падеже')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус')),
                ('types', models.ManyToManyField(related_name='subjects', to='trial_exam.examtype', verbose_name='Тип экзамена')),
            ],
        ),
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_exam', models.TimeField(verbose_name='Начало проведения')),
                ('end_exam', models.TimeField(verbose_name='Окончание экзамена')),
                ('available_slots', models.PositiveIntegerField(verbose_name='Количество свободных мест')),
                ('weekday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trial_exam.weekday', verbose_name='День недели')),
            ],
        ),
        migrations.CreateModel(
            name='ExamRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата провдения')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trial_exam.subject')),
                ('time_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trial_exam.examschedule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myclass.student')),
            ],
        ),
    ]
