# Generated by Django 4.2.15 on 2025-01-11 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial_exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examtype',
            name='type',
            field=models.CharField(choices=[('ЕГЭ', 'ЕГЭ'), ('ОГЭ', 'ОГЭ')], max_length=3, verbose_name='Тип экзамена'),
        ),
    ]
